# Fig pre block. Keep at the top of this file.
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/.local/share/nodejs/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH

export ZSH_DISABLE_COMPFIX=true

ZSH_THEME='code-smell'
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'
export BAT_THEME="1337"

source $HOME/.config/zsh/zshrc.core.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
